using System.Linq;
using Content.Client.Humanoid;
using Content.Shared._Sunrise.DynamicAppearance;
using Content.Shared._Sunrise.SunriseCCVars;
using Content.Shared._Sunrise.TTS;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.DynamicAppearance;

[GenerateTypedNameReferences]
public sealed partial class DynamicAppearanceWindow : DefaultWindow
{
    /// <summary>Fired when the user presses Save.</summary>
    public event Action? OnSave;

    /// <summary>Fired when the user presses Reset.</summary>
    public event Action? OnReset;

    // Dependencies
    private readonly IPrototypeManager _protoMan;
    private readonly MarkingManager _markingManager;
    private readonly IConfigurationManager _cfg;

    // State
    private DynamicAppearanceState _draftState = new(
        new MarkingSet(),
        string.Empty,
        Sex.Male,
        0,
        Gender.Male,
        string.Empty,
        Color.White,
        Color.White,
        new Dictionary<HumanoidVisualLayers, CustomBaseLayerInfo>(),
        100f,
        100f
    );

    public DynamicAppearanceState DraftState
    {
        get => _draftState;
        private set => _draftState = value;
    }

    // Controls
    private ColorSelectorSliders _skinColorSelector = default!; // Inits in InitSkinColorUI

    // OptionButton value lists
    private readonly List<Sex> _sexValues = new();
    private readonly List<Gender> _genderValues = new();
    private List<TTSVoicePrototype> _filteredVoices = new();
    private readonly bool _ttsEnabled;

    // Cached data about user
    private SpeciesPrototype? _speciesProto;

    public DynamicAppearanceWindow()
    {
        RobustXamlLoader.Load(this);

        _protoMan = IoCManager.Resolve<IPrototypeManager>();
        _markingManager = IoCManager.Resolve<MarkingManager>();
        _cfg = IoCManager.Resolve<IConfigurationManager>();

        _ttsEnabled = _cfg.GetCVar(SunriseCCVars.TTSEnabled);
        TTSContainer.Visible = _ttsEnabled;

        InitSaveResetUI();
        InitAgeUI();
        InitSexUI();
        InitPronounsUI();
        InitVoiceUI();
        InitSizeUI();
        InitColorUI();
        InitMarkingUI();
    }

    /// <summary>
    /// Pushes a full server state into every control and resets the draft.
    /// </summary>
    public void UpdateState(DynamicAppearanceBUIState state)
    {
        _draftState = state.State;

        _speciesProto = _protoMan.TryIndex<SpeciesPrototype>(_draftState.Species, out var sp) ? sp : null;

        // Age
        AgeEdit.Text = _draftState.Age.ToString();

        // Sex
        RebuildSexButton();

        // Pronouns
        var genderIdx = _genderValues.IndexOf(_draftState.Gender);
        if (genderIdx >= 0) PronounsButton.SelectId(genderIdx);

        // TTS
        if (_ttsEnabled) UpdateVoiceList();

        // Size sliders
        if (_speciesProto != null)
        {
            HeightSlider.MinValue = _speciesProto.MinHeight;
            HeightSlider.MaxValue = _speciesProto.MaxHeight;
            WidthSlider.MinValue = _speciesProto.MinWidth;
            WidthSlider.MaxValue = _speciesProto.MaxWidth;
        }
        HeightSlider.Value = _draftState.Height;
        WidthSlider.Value = _draftState.Width;
        UpdateSizeLabels();

        // Colors
        _skinColorSelector.Color = _draftState.SkinColor;
        EyeColorPicker.SetData(_draftState.EyeColor);

        // Hair
        RefreshHairPickers();

        // Body markings
        Markings.SetData(_draftState.MarkingSet, _draftState.Species, _draftState.Sex, _draftState.SkinColor, _draftState.EyeColor);
    }

    // =========================================================================
    //  Private helpers
    // =========================================================================

    private void InitSaveResetUI()
    {
        SaveButton.OnPressed += _ => OnSave?.Invoke();
        ResetButton.OnPressed += _ => OnReset?.Invoke();
    }

    private void InitAgeUI()
    {
        AgeEdit.OnTextChanged += args => _draftState.Age = int.TryParse(args.Text, out var age) ? age : _draftState.Age;
    }

    private void InitSexUI()
    {
        SexButton.OnItemSelected += args =>
        {
            _draftState.Sex = _sexValues[args.Id];
            SexButton.SelectId(args.Id);
            if (_ttsEnabled)
                UpdateVoiceList();
            RefreshBodyMarkings();
        };
    }

    private void InitPronounsUI()
    {
        foreach (Gender gender in Enum.GetValues<Gender>())
        {
            PronounsButton.AddItem(
                Loc.GetString($"humanoid-profile-editor-pronouns-{gender.ToString().ToLowerInvariant()}-text"),
                _genderValues.Count
            );
            _genderValues.Add(gender);
        }
        PronounsButton.OnItemSelected += args =>
        {
            _draftState.Gender = _genderValues[args.Id];
            PronounsButton.SelectId(args.Id);
        };
    }

    private void InitVoiceUI()
    {
        VoiceButton.OnItemSelected += args =>
        {
            if (args.Id < _filteredVoices.Count)
            {
                _draftState.Voice = _filteredVoices[args.Id].ID;
                VoiceButton.SelectId(args.Id);
            }
        };
        VoicePlayButton.OnPressed += _ => { /* TODO: TTS preview stub */ };
    }

    private void InitSizeUI()
    {
        InitWidthUI();
        InitHeightUI();
    }

    private void InitWidthUI()
    {
        WidthSlider.OnValueChanged += _ =>
        {
            UpdateSizeLabels();
        };

        WidthSlider.OnReleased += _ =>
        {
            _draftState.Width = WidthSlider.Value;
        };

        WidthResetButton.OnPressed += _ =>
        {
            if (_speciesProto == null) return;
            WidthSlider.Value = _speciesProto.DefaultWidth;
            _draftState.Width = _speciesProto.DefaultWidth;
            UpdateSizeLabels();
        };
    }

    private void InitHeightUI()
    {
        HeightSlider.OnValueChanged += _ =>
        {
            UpdateSizeLabels();
        };
        HeightSlider.OnReleased += _ =>
        {
            _draftState.Height = HeightSlider.Value;
        };
        HeightResetButton.OnPressed += _ =>
        {
            if (_speciesProto == null) return;
            HeightSlider.Value = _speciesProto.DefaultHeight;
            _draftState.Height = _speciesProto.DefaultHeight;
            UpdateSizeLabels();
        };
    }

    private void InitColorUI()
    {
        InitSkinColorUI();
        InitEyeColorUI();
    }

    private void InitSkinColorUI()
    {
        _skinColorSelector = new ColorSelectorSliders
        {
            SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv
        };
        SkinColorContainer.AddChild(_skinColorSelector);
        _skinColorSelector.OnColorChanged += color => _draftState.SkinColor = color;
    }

    private void InitEyeColorUI()
    {
        EyeColorPicker.OnEyeColorPicked += color => _draftState.EyeColor = color;
    }

    private void InitMarkingUI()
    {
        // Hair pickers sync changes directly into _draftState
        HairPicker.OnMarkingSelect += args => ApplyMarkingSelect(MarkingCategories.Hair, args.slot, args.id);
        HairPicker.OnColorChanged += args => ApplyMarkingColor(MarkingCategories.Hair, args.slot, args.marking);
        HairPicker.OnSlotRemove += slot => _draftState.MarkingSet.Remove(MarkingCategories.Hair, slot);
        HairPicker.OnSlotAdd += () => { };

        FacialHairPicker.OnMarkingSelect += args => ApplyMarkingSelect(MarkingCategories.FacialHair, args.slot, args.id);
        FacialHairPicker.OnColorChanged += args => ApplyMarkingColor(MarkingCategories.FacialHair, args.slot, args.marking);
        FacialHairPicker.OnSlotRemove += slot => _draftState.MarkingSet.Remove(MarkingCategories.FacialHair, slot);
        FacialHairPicker.OnSlotAdd += () => { };

        // Body markings  MarkingPicker passes back its internal set on every change
        Markings.OnMarkingAdded += set => _draftState.MarkingSet = set;
        Markings.OnMarkingRemoved += set => _draftState.MarkingSet = set;
        Markings.OnMarkingColorChange += set => _draftState.MarkingSet = set;
        Markings.OnMarkingRankChange += set => _draftState.MarkingSet = set;
    }

    private void RebuildSexButton()
    {
        _sexValues.Clear();
        SexButton.Clear();
        if (_speciesProto == null) return;

        foreach (var sex in _speciesProto.Sexes)
        {
            SexButton.AddItem(
                Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLowerInvariant()}-text"),
                _sexValues.Count);
            _sexValues.Add(sex);
        }

        var idx = _sexValues.IndexOf(_draftState.Sex);
        if (idx >= 0)
            SexButton.SelectId(idx);
        else if (_sexValues.Count > 0)
        {
            SexButton.SelectId(0);
            _draftState.Sex = _sexValues[0];
        }
    }

    private void UpdateVoiceList()
    {
        _filteredVoices = _protoMan.EnumeratePrototypes<TTSVoicePrototype>()
            .Where(v => v.RoundStart && HumanoidCharacterProfile.CanHaveVoice(v, _draftState.Sex))
            .OrderBy(v => v.Name)
            .ToList();

        VoiceButton.Clear();
        var selectIdx = 0;
        for (var i = 0; i < _filteredVoices.Count; i++)
        {
            var voice = _filteredVoices[i];
            VoiceButton.AddItem(voice.Name, i);
            if (voice.ID == _draftState.Voice)
                selectIdx = i;
        }

        if (_filteredVoices.Count > 0)
        {
            VoiceButton.SelectId(selectIdx);
            _draftState.Voice = _filteredVoices[selectIdx].ID;
        }
    }

    private void UpdateSizeLabels()
    {
        HeightLabel.Text = Loc.GetString("dynamic-appearance-height-label", ("value", (int)Math.Round(HeightSlider.Value * 100f)));
        WidthLabel.Text = Loc.GetString("dynamic-appearance-width-label", ("value", (int)Math.Round(WidthSlider.Value * 100f)));
    }

    private void RefreshHairPickers()
    {
        var hairList = _draftState.MarkingSet.TryGetCategory(MarkingCategories.Hair, out var h)
            ? h.ToList() : new List<Marking>();
        var facialList = _draftState.MarkingSet.TryGetCategory(MarkingCategories.FacialHair, out var fh)
            ? fh.ToList() : new List<Marking>();

        HairPicker.UpdateData(hairList, _draftState.Species, 1);
        FacialHairPicker.UpdateData(facialList, _draftState.Species, 1);
    }

    private void RefreshBodyMarkings()
    {
        Markings.SetData(_draftState.MarkingSet, _draftState.Species, _draftState.Sex, _draftState.SkinColor, _draftState.EyeColor);
    }

    private void ApplyMarkingSelect(MarkingCategories category, int slot, string newId)
    {
        if (!_protoMan.TryIndex<MarkingPrototype>(newId, out var proto)) return;

        if (_draftState.MarkingSet.TryGetCategory(category, out var list) && slot < list.Count)
            _draftState.MarkingSet.Replace(category, slot, new Marking(newId, proto.Sprites.Count));
        else
            _draftState.MarkingSet.AddBack(category, new Marking(newId, proto.Sprites.Count));
    }

    private void ApplyMarkingColor(MarkingCategories category, int slot, Marking updated)
    {
        if (_draftState.MarkingSet.TryGetCategory(category, out var list) && slot < list.Count)
            _draftState.MarkingSet.Replace(category, slot, updated);
    }
}
