using System.Linq;
using Content.Client.Humanoid;
using Content.Shared._Sunrise.DynamicAppearance;
using Content.Shared._Sunrise.SunriseCCVars;
using Content.Shared._Sunrise.TTS;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.DynamicAppearance;

[GenerateTypedNameReferences]
public sealed partial class DynamicAppearanceWindow : DefaultWindow
{
    /// <summary>Fired when the user presses Save.</summary>
    public event Action? OnSave;

    /// <summary>Fired when the user presses Reset.</summary>
    public event Action? OnReset;

    private readonly IPrototypeManager _protoMan;
    private readonly MarkingManager _markingManager;
    private readonly IConfigurationManager _cfg;
    private readonly ColorSelectorSliders _skinColorSelector;

    // Draft state (mutated by controls; sent to server only on Save)
    private Sex _draftSex;
    private int _draftAge;
    private Gender _draftGender;
    private string _draftVoice = string.Empty;
    private Color _draftSkinColor;
    private Color _draftEyeColor;
    private MarkingSet _draftMarkings = new();
    private string _draftSpecies = string.Empty;
    private Dictionary<HumanoidVisualLayers, CustomBaseLayerInfo> _draftBaseLayers = new();

    // OptionButton value lists
    private readonly List<Sex> _sexValues = new();
    private readonly List<Gender> _genderValues = new();
    private List<TTSVoicePrototype> _filteredVoices = new();
    private readonly bool _ttsEnabled;

    private SpeciesPrototype? _speciesProto;

    /// <summary>Set during UpdateState to prevent re-entrant change events.</summary>
    private bool _loading;

    public DynamicAppearanceWindow()
    {
        RobustXamlLoader.Load(this);

        _protoMan = IoCManager.Resolve<IPrototypeManager>();
        _markingManager = IoCManager.Resolve<MarkingManager>();
        _cfg = IoCManager.Resolve<IConfigurationManager>();

        _ttsEnabled = _cfg.GetCVar(SunriseCCVars.TTSEnabled);
        TTSContainer.Visible = _ttsEnabled;

        // Skin color selector
        _skinColorSelector = new ColorSelectorSliders
        {
            SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv
        };
        SkinColorContainer.AddChild(_skinColorSelector);
        _skinColorSelector.OnColorChanged += color =>
        {
            if (_loading) return;
            _draftSkinColor = color;
        };

        // Eye color
        EyeColorPicker.OnEyeColorPicked += color =>
        {
            if (_loading) return;
            _draftEyeColor = color;
        };

        // Age
        AgeEdit.OnTextChanged += args =>
        {
            if (_loading) return;
            if (int.TryParse(args.Text, out var age))
                _draftAge = age;
        };

        // Sex
        SexButton.OnItemSelected += args =>
        {
            if (_loading) return;
            if (args.Id < _sexValues.Count)
                _draftSex = _sexValues[args.Id];
            if (_ttsEnabled) UpdateVoiceList();
            RefreshBodyMarkings();
        };

        // Pronouns  static list built once
        foreach (Gender g in Enum.GetValues<Gender>())
        {
            PronounsButton.AddItem(
                Loc.GetString($"humanoid-profile-editor-pronouns-{g.ToString().ToLowerInvariant()}-text"),
                _genderValues.Count);
            _genderValues.Add(g);
        }
        PronounsButton.OnItemSelected += args =>
        {
            if (_loading) return;
            if (args.Id < _genderValues.Count)
                _draftGender = _genderValues[args.Id];
        };

        // TTS voice
        VoiceButton.OnItemSelected += args =>
        {
            if (_loading) return;
            if (args.Id < _filteredVoices.Count)
                _draftVoice = _filteredVoices[args.Id].ID;
        };
        VoicePlayButton.OnPressed += _ => { /* TTS preview stub */ };

        // Height slider
        HeightSlider.OnValueChanged += _ =>
        {
            if (_loading) return;
            UpdateSizeLabels();
        };
        HeightResetButton.OnPressed += _ =>
        {
            if (_speciesProto == null) return;
            _loading = true;
            HeightSlider.Value = _speciesProto.DefaultHeight;
            _loading = false;
            UpdateSizeLabels();
        };

        // Width slider
        WidthSlider.OnValueChanged += _ =>
        {
            if (_loading) return;
            UpdateSizeLabels();
        };
        WidthResetButton.OnPressed += _ =>
        {
            if (_speciesProto == null) return;
            _loading = true;
            WidthSlider.Value = _speciesProto.DefaultWidth;
            _loading = false;
            UpdateSizeLabels();
        };

        // Hair pickers  sync changes directly into _draftMarkings
        HairPicker.OnMarkingSelect += args => ApplyMarkingSelect(MarkingCategories.Hair, args.slot, args.id);
        HairPicker.OnColorChanged += args => ApplyMarkingColor(MarkingCategories.Hair, args.slot, args.marking);
        HairPicker.OnSlotRemove += slot => _draftMarkings.Remove(MarkingCategories.Hair, slot);
        HairPicker.OnSlotAdd += () => { };

        FacialHairPicker.OnMarkingSelect += args => ApplyMarkingSelect(MarkingCategories.FacialHair, args.slot, args.id);
        FacialHairPicker.OnColorChanged += args => ApplyMarkingColor(MarkingCategories.FacialHair, args.slot, args.marking);
        FacialHairPicker.OnSlotRemove += slot => _draftMarkings.Remove(MarkingCategories.FacialHair, slot);
        FacialHairPicker.OnSlotAdd += () => { };

        // Body markings  MarkingPicker passes back its internal set on every change
        Markings.OnMarkingAdded += set => _draftMarkings = set;
        Markings.OnMarkingRemoved += set => _draftMarkings = set;
        Markings.OnMarkingColorChange += set => _draftMarkings = set;
        Markings.OnMarkingRankChange += set => _draftMarkings = set;

        // Save / Reset buttons
        SaveButton.OnPressed += _ => OnSave?.Invoke();
        ResetButton.OnPressed += _ => OnReset?.Invoke();
    }

    /// <summary>
    /// Pushes a full server state into every control and resets the draft.
    /// </summary>
    public void UpdateState(DynamicAppearanceState state)
    {
        _loading = true;
        try
        {
            _draftSpecies = state.Species;
            _draftSex = state.Sex;
            _draftAge = state.Age;
            _draftGender = state.Gender;
            _draftVoice = state.Voice;
            _draftSkinColor = state.SkinColor;
            _draftEyeColor = state.EyeColor;
            _draftMarkings = new MarkingSet(state.MarkingSet);
            _draftBaseLayers = state.CustomBaseLayers;

            _speciesProto = _protoMan.TryIndex<SpeciesPrototype>(state.Species, out var sp) ? sp : null;

            // Age
            AgeEdit.Text = state.Age.ToString();

            // Sex
            RebuildSexButton();

            // Pronouns
            var genderIdx = _genderValues.IndexOf(state.Gender);
            if (genderIdx >= 0) PronounsButton.SelectId(genderIdx);

            // TTS
            if (_ttsEnabled) UpdateVoiceList();

            // Size sliders
            if (_speciesProto != null)
            {
                HeightSlider.MinValue = _speciesProto.MinHeight;
                HeightSlider.MaxValue = _speciesProto.MaxHeight;
                WidthSlider.MinValue = _speciesProto.MinWidth;
                WidthSlider.MaxValue = _speciesProto.MaxWidth;
            }
            HeightSlider.Value = state.Height;
            WidthSlider.Value = state.Width;
            UpdateSizeLabels();

            // Colors
            _skinColorSelector.Color = state.SkinColor;
            EyeColorPicker.SetData(state.EyeColor);

            // Hair
            RefreshHairPickers();

            // Body markings
            Markings.SetData(_draftMarkings, state.Species, state.Sex, state.SkinColor, state.EyeColor);
        }
        finally
        {
            _loading = false;
        }
    }

    /// <summary>Builds the save message from current draft state.</summary>
    public DynamicAppearanceSaveMessage BuildSaveMessage()
    {
        return new DynamicAppearanceSaveMessage(
            _draftMarkings,
            _draftSex,
            _draftAge,
            _draftGender,
            _draftVoice,
            _draftSkinColor,
            _draftEyeColor,
            _draftBaseLayers,
            WidthSlider.Value,
            HeightSlider.Value);
    }

    // =========================================================================
    //  Private helpers
    // =========================================================================

    private void RebuildSexButton()
    {
        _sexValues.Clear();
        SexButton.Clear();
        if (_speciesProto == null) return;

        foreach (var sex in _speciesProto.Sexes)
        {
            SexButton.AddItem(
                Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLowerInvariant()}-text"),
                _sexValues.Count);
            _sexValues.Add(sex);
        }

        var idx = _sexValues.IndexOf(_draftSex);
        if (idx >= 0)
            SexButton.SelectId(idx);
        else if (_sexValues.Count > 0)
        {
            SexButton.SelectId(0);
            _draftSex = _sexValues[0];
        }
    }

    private void UpdateVoiceList()
    {
        _filteredVoices = _protoMan.EnumeratePrototypes<TTSVoicePrototype>()
            .Where(v => v.RoundStart && HumanoidCharacterProfile.CanHaveVoice(v, _draftSex))
            .OrderBy(v => v.Name)
            .ToList();

        VoiceButton.Clear();
        var selectIdx = 0;
        for (var i = 0; i < _filteredVoices.Count; i++)
        {
            var voice = _filteredVoices[i];
            VoiceButton.AddItem(voice.Name, i);
            if (voice.ID == _draftVoice)
                selectIdx = i;
        }

        if (_filteredVoices.Count > 0)
        {
            VoiceButton.SelectId(selectIdx);
            _draftVoice = _filteredVoices[selectIdx].ID;
        }
    }

    private void UpdateSizeLabels()
    {
        HeightLabel.Text = Loc.GetString("dynamic-appearance-height-label", ("value", (int)Math.Round(HeightSlider.Value * 100f)));
        WidthLabel.Text = Loc.GetString("dynamic-appearance-width-label", ("value", (int)Math.Round(WidthSlider.Value * 100f)));
    }

    private void RefreshHairPickers()
    {
        var hairList = _draftMarkings.TryGetCategory(MarkingCategories.Hair, out var h)
            ? h.ToList() : new List<Marking>();
        var facialList = _draftMarkings.TryGetCategory(MarkingCategories.FacialHair, out var fh)
            ? fh.ToList() : new List<Marking>();

        HairPicker.UpdateData(hairList, _draftSpecies, 1);
        FacialHairPicker.UpdateData(facialList, _draftSpecies, 1);
    }

    private void RefreshBodyMarkings()
    {
        Markings.SetData(_draftMarkings, _draftSpecies, _draftSex, _draftSkinColor, _draftEyeColor);
    }

    private void ApplyMarkingSelect(MarkingCategories category, int slot, string newId)
    {
        if (!_protoMan.TryIndex<MarkingPrototype>(newId, out var proto)) return;

        if (_draftMarkings.TryGetCategory(category, out var list) && slot < list.Count)
            _draftMarkings.Replace(category, slot, new Marking(newId, proto.Sprites.Count));
        else
            _draftMarkings.AddBack(category, new Marking(newId, proto.Sprites.Count));
    }

    private void ApplyMarkingColor(MarkingCategories category, int slot, Marking updated)
    {
        if (_draftMarkings.TryGetCategory(category, out var list) && slot < list.Count)
            _draftMarkings.Replace(category, slot, updated);
    }
}
